parameters:
#    polcode_unit_converter.example.class: Polcode\UnitConverterBundle\Example

services:
#    polcode_unit_converter.example:
#        class: %polcode_unit_converter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
